import type { DashboardData } from "../types/dashboard.types";

export const QUICK_PROMPTS = [
  "How much Urea per acre for Wheat?",
  "Yellow rust symptoms on Wheat",
  "Will it rain in Karnal tomorrow?",
  "Current Mandi price of Mustard",
];

export const DEFAULT_DASHBOARD_DATA: DashboardData = {
  profile: {
    name: "Farmer",
    greetingPrefix: "Hello",
    village: "Karnal",
    district: "Karnal",
    state: "Haryana",
    activeCrop: "Wheat",
    cropSeason: "Rabi",
    farmSizeAcres: 12,
  },
  emergencyAlert: undefined,
  weatherSummary: {
    temperatureC: 28,
    feelsLikeC: 31,
    condition: "partly-cloudy",
    humidity: 65,
    windSpeedKmh: 14,
    advisory: "Moderate conditions. Safe for most field operations.",
    advisorySafe: true,
  },
  cropFields: [
    {
      id: "field-1",
      fieldName: "Block A",
      cropName: "Wheat",
      healthPercent: 92,
      status: "healthy",
      lastScanResult: "No issues detected",
      lastScanDate: new Date(),
      nextAction: "Irrigate in 2 days",
    },
    {
      id: "field-2",
      fieldName: "Block B",
      cropName: "Mustard",
      healthPercent: 78,
      status: "at_risk",
      lastScanResult: "Early signs of aphid infestation",
      lastScanDate: new Date(),
      nextAction: "Apply neem oil spray",
    },
  ],
  cropHealthCards: [
    {
      id: "crop-1",
      cropName: "Wheat",
      blockName: "Block A",
      daysSinceSown: 45,
      status: "healthy",
      moisturePercent: 72,
      recommendation: "Continue regular irrigation schedule",
    },
    {
      id: "crop-2",
      cropName: "Mustard",
      blockName: "Block B",
      daysSinceSown: 30,
      status: "alert",
      moisturePercent: 55,
      alertMessage: "Aphid infestation detected",
      recommendation: "Apply neem oil spray within 24 hours",
    },
    {
      id: "crop-3",
      cropName: "Gram",
      blockName: "Block C",
      daysSinceSown: 60,
      status: "healthy",
      moisturePercent: 68,
      recommendation: "Apply second dose of fertiliser next week",
    },
  ],
  mandiPrices: [
    {
      id: "mandi-1",
      commodity: "Wheat",
      variety: "HD-3086",
      mandiName: "Karnal Mandi",
      pricePerQuintal: 2275,
      changeAmount: 45,
      changePercent: 2.01,
      isRise: true,
      mspDifference: 175,
      updatedAt: new Date(),
    },
    {
      id: "mandi-2",
      commodity: "Mustard",
      variety: "Bold",
      mandiName: "Karnal Mandi",
      pricePerQuintal: 5420,
      changeAmount: -80,
      changePercent: -1.45,
      isRise: false,
      mspDifference: 220,
      updatedAt: new Date(),
    },
    {
      id: "mandi-3",
      commodity: "Gram",
      variety: "Desi",
      mandiName: "Karnal Mandi",
      pricePerQuintal: 5150,
      changeAmount: 30,
      changePercent: 0.58,
      isRise: true,
      mspDifference: 150,
      updatedAt: new Date(),
    },
  ],
  marketTrends: [
    {
      id: "trend-1",
      commodity: "Wheat",
      price: "₹2,275/q",
      changePercent: 2.01,
      isRise: true,
    },
    {
      id: "trend-2",
      commodity: "Mustard",
      price: "₹5,420/q",
      changePercent: -1.45,
      isRise: false,
    },
    {
      id: "trend-3",
      commodity: "Gram",
      price: "₹5,150/q",
      changePercent: 0.58,
      isRise: true,
    },
    {
      id: "trend-4",
      commodity: "Rice",
      price: "₹3,180/q",
      changePercent: 0.32,
      isRise: true,
    },
    {
      id: "trend-5",
      commodity: "Cotton",
      price: "₹6,450/q",
      changePercent: -0.78,
      isRise: false,
    },
  ],
  aiAdvisorChats: [
    {
      id: "chat-1",
      title: "Irrigation Schedule",
      description:
        "Block A needs irrigation in 2 days. Soil moisture at 72% — optimal range.",
      timestamp: "2 hours ago",
      iconType: "water",
    },
    {
      id: "chat-2",
      title: "Pest Alert — Block B",
      description:
        "Aphid activity detected on Mustard. Apply neem oil spray immediately.",
      timestamp: "5 hours ago",
      iconType: "pest",
    },
    {
      id: "chat-3",
      title: "Fertiliser Reminder",
      description:
        "Second dose of Urea due for Gram crop next Monday. Estimated 40kg/acre.",
      timestamp: "1 day ago",
      iconType: "fertilizer",
    },
    {
      id: "chat-4",
      title: "Weather Advisory",
      description:
        "Rain expected Saturday. Postpone any spraying operations until Sunday.",
      timestamp: "1 day ago",
      iconType: "weather",
    },
  ],
  priorityAlerts: [
    {
      id: "alert-1",
      title: "Frost Warning — Saturday Night",
      description:
        "Temperature expected to drop below 2°C. Cover sensitive crops and delay irrigation.",
      type: "frost",
      borderColor: "border-blue-500",
    },
    {
      id: "alert-2",
      title: "PM-KISAN Subsidy Deadline",
      description:
        "Application deadline in 3 days. Ensure all documents are uploaded.",
      type: "subsidy",
      borderColor: "border-emerald-500",
    },
    {
      id: "alert-3",
      title: "Heavy Rain Alert — Saturday",
      description: "50-80mm rainfall expected. Ensure field drainage is clear.",
      type: "weather",
      borderColor: "border-amber-500",
    },
  ],
  schemes: [
    {
      id: "scheme-1",
      title: "PM-KISAN",
      category: "Income Support",
      benefitAmount: "₹6,000/year",
      statusBadge: "Eligible",
      deadline: "31 Dec 2026",
      summary: "Direct income support for small and marginal farmers.",
    },
    {
      id: "scheme-2",
      title: "Pradhan Mantri Fasal Bima Yojana",
      category: "Crop Insurance",
      benefitAmount: "Up to 90% premium subsidy",
      statusBadge: "Eligible",
      deadline: "15 Jan 2027",
      summary: "Comprehensive crop insurance scheme for farmers.",
    },
    {
      id: "scheme-3",
      title: "Kisan Credit Card",
      category: "Credit",
      benefitAmount: "Up to ₹3 lakh at 4% p.a.",
      statusBadge: "Applied",
      summary: "Credit facility for agricultural needs.",
    },
    {
      id: "scheme-4",
      title: "Soil Health Card",
      category: "Soil Testing",
      benefitAmount: "Free soil testing",
      statusBadge: "Approved",
      summary: "Get soil tested and receive fertiliser recommendations.",
    },
  ],
  recentActivities: [
    {
      id: "activity-1",
      type: "scan",
      title: "Crop scan completed",
      description: "Block A — Wheat crop healthy at 92%",
      timestamp: new Date(Date.now() - 2 * 60 * 60 * 1000),
    },
    {
      id: "activity-2",
      type: "chat",
      title: "AI Advisor consultation",
      description: "Asked about aphid treatment for Mustard crop",
      timestamp: new Date(Date.now() - 5 * 60 * 60 * 1000),
    },
    {
      id: "activity-3",
      type: "mandi",
      title: "Market price checked",
      description: "Wheat price updated — ₹2,275/quintal",
      timestamp: new Date(Date.now() - 8 * 60 * 60 * 1000),
    },
    {
      id: "activity-4",
      type: "scheme",
      title: "Scheme application",
      description: "Applied for Kisan Credit Card",
      timestamp: new Date(Date.now() - 24 * 60 * 60 * 1000),
    },
    {
      id: "activity-5",
      type: "irrigation",
      title: "Irrigation completed",
      description: "Block A — 45 minutes of drip irrigation",
      timestamp: new Date(Date.now() - 48 * 60 * 60 * 1000),
    },
  ],
  notifications: [
    {
      id: "notif-1",
      category: "alert",
      title: "Frost Warning",
      message: "Frost expected Saturday night. Protect sensitive crops.",
      timestamp: new Date(Date.now() - 30 * 60 * 1000),
      read: false,
    },
    {
      id: "notif-2",
      category: "reminder",
      title: "Irrigation Reminder",
      message: "Block A needs irrigation within 2 days.",
      timestamp: new Date(Date.now() - 2 * 60 * 60 * 1000),
      read: false,
    },
    {
      id: "notif-3",
      category: "update",
      title: "Market Price Update",
      message: "Wheat price increased by 2.01% today.",
      timestamp: new Date(Date.now() - 4 * 60 * 60 * 1000),
      read: true,
    },
    {
      id: "notif-4",
      category: "alert",
      title: "Pest Detection",
      message: "Aphid activity found on Mustard in Block B.",
      timestamp: new Date(Date.now() - 6 * 60 * 60 * 1000),
      read: true,
    },
    {
      id: "notif-5",
      category: "reminder",
      title: "Scheme Deadline",
      message: "PM-KISAN application deadline in 3 days.",
      timestamp: new Date(Date.now() - 24 * 60 * 60 * 1000),
      read: true,
    },
  ],
};
