// ─────────────────────────────────────────────────────────────────────────────
// memory.constants.ts
// KisanGPT — Farm Memory feature constants & mock items
// ─────────────────────────────────────────────────────────────────────────────

import type {
  FarmMemoryItem,
  PersonalizedRecommendation,
  MemoryCategoryConfig,
  AIMemoryInsight,
  MemoryHeroStats,
} from "../types/memory.types";

export const MEMORY_CATEGORIES: MemoryCategoryConfig[] = [
  {
    id: "soil",
    label: "Soil & Land",
    labelHi: "मिट्टी और भूमि",
    icon: "Layers",
    color: "text-amber-600",
    bg: "bg-amber-500/10",
    description: "Soil tests, pH levels, nutrient data",
  },
  {
    id: "crop_yield",
    label: "Crop History",
    labelHi: "फसल इतिहास",
    icon: "Wheat",
    color: "text-emerald-600",
    bg: "bg-emerald-500/10",
    description: "Harvest yields, crop cycles, planting logs",
  },
  {
    id: "disease_history",
    label: "Disease Reports",
    labelHi: "बीमारी रिपोर्ट",
    icon: "Bug",
    color: "text-red-500",
    bg: "bg-red-500/10",
    description: "Disease detection, treatments, resolutions",
  },
  {
    id: "irrigation",
    label: "Irrigation",
    labelHi: "सिंचाई रिकॉर्ड",
    icon: "Droplets",
    color: "text-blue-500",
    bg: "bg-blue-500/10",
    description: "Water usage, drip systems, canal schedules",
  },
  {
    id: "fertilizer",
    label: "Fertilizers",
    labelHi: "उर्वरक उपयोग",
    icon: "FlaskConical",
    color: "text-purple-500",
    bg: "bg-purple-500/10",
    description: "NPK applications, dosage records",
  },
  {
    id: "weather_decisions",
    label: "Weather Decisions",
    labelHi: "मौसम निर्णय",
    icon: "Cloud",
    color: "text-sky-500",
    bg: "bg-sky-500/10",
    description: "Weather-based farming decisions",
  },
  {
    id: "market_decisions",
    label: "Market Decisions",
    labelHi: "बाज़ार निर्णय",
    icon: "TrendingUp",
    color: "text-violet-500",
    bg: "bg-violet-500/10",
    description: "Selling prices, mandi visits, market alerts",
  },
  {
    id: "govt_schemes",
    label: "Govt Schemes",
    labelHi: "सरकारी योजनाएं",
    icon: "Shield",
    color: "text-indigo-500",
    bg: "bg-indigo-500/10",
    description: "Scheme applications, eligibility, updates",
  },
  {
    id: "voice_conversations",
    label: "Voice Conversations",
    labelHi: "वॉयस बातचीत",
    icon: "Mic",
    color: "text-pink-500",
    bg: "bg-pink-500/10",
    description: "Voice queries and AI responses",
  },
  {
    id: "saved_ai_advice",
    label: "Saved AI Advice",
    labelHi: "सहेजी गई सलाह",
    icon: "Bookmark",
    color: "text-teal-500",
    bg: "bg-teal-500/10",
    description: "Bookmarked AI recommendations",
  },
  {
    id: "custom_note",
    label: "Farm Notes",
    labelHi: "किसान नोट्स",
    icon: "FileText",
    color: "text-gray-500",
    bg: "bg-gray-500/10",
    description: "Personal notes and observations",
  },
];

export const MOCK_FARM_MEMORIES: FarmMemoryItem[] = [
  {
    id: "mem-1",
    category: "soil",
    title: "Karnal Farm Soil Test Results",
    description:
      "Soil analysis indicates pH 7.2 with slight deficiency in Organic Carbon (0.42%) and Potassium. Recommended addition of farmyard manure and MOP application.",
    timestamp: "2026-06-15T10:30:00Z",
    location: "Karnal, Haryana",
    cropName: "Wheat / Paddy Rotation",
    metrics: { ph: 7.2, nitrogen: 180, phosphorus: 22, potassium: 110 },
    tags: ["Soil Health", "Karnal", "Organic Carbon", "pH Test"],
    isVerified: true,
    isPinned: true,
    isSaved: true,
    importance: "high",
    source: "manual",
    aiExplanation:
      "Your soil pH is within optimal range for wheat cultivation. However, the low Organic Carbon (0.42%) indicates depleted organic matter. Adding farmyard manure at 5-7 tonnes/acre will improve soil structure and water retention capacity.",
    updatedAt: "2026-06-15T10:30:00Z",
  },
  {
    id: "mem-2",
    category: "crop_yield",
    title: "Rabi Season Wheat Harvesting Yield (PBW 550)",
    description:
      "Harvested 24.5 quintals per acre across Field 2. Sold at Karnal APMC Mandi at ₹2,275/qtl. Total revenue: ₹1,66,625 from 3 acres.",
    timestamp: "2026-04-20T14:15:00Z",
    location: "Karnal, Haryana",
    cropName: "Wheat (PBW 550)",
    season: "Rabi 2025-26",
    metrics: { yield_quintals: 24.5, area_acres: 3 },
    tags: ["Rabi", "Wheat", "Mandi", "PBW 550", "Revenue"],
    isVerified: true,
    isPinned: false,
    isSaved: true,
    importance: "high",
    source: "manual",
    aiExplanation:
      "Your wheat yield of 24.5 qtl/acre is above the Haryana state average of 22 qtl/acre. PBW 550 variety performed well under your soil conditions. Consider maintaining the same seed variety for the next Rabi season.",
    updatedAt: "2026-04-20T14:15:00Z",
  },
  {
    id: "mem-3",
    category: "disease_history",
    title: "Yellow Rust Spotting in Wheat Crop",
    description:
      "Spotted early yellow rust lesions on lower leaves. Treated with Propiconazole 25% EC (200ml/acre) within 48 hours. Spread successfully arrested. No further recurrence observed.",
    timestamp: "2026-02-10T09:00:00Z",
    location: "Karnal, Haryana",
    cropName: "Wheat",
    season: "Rabi 2025-26",
    tags: ["Yellow Rust", "Fungicide", "Resolved", "Propiconazole"],
    isVerified: true,
    isPinned: true,
    isSaved: false,
    importance: "high",
    source: "scan",
    relatedConversationId: "conv-disease-001",
    aiExplanation:
      "Yellow rust (Puccinia striiformis) was detected early on lower leaves. Quick action with Propiconazole prevented crop damage. For future Rabi seasons, monitor leaves weekly during foggy December-February periods when humidity favors rust development.",
    updatedAt: "2026-02-12T09:00:00Z",
  },
  {
    id: "mem-4",
    category: "irrigation",
    title: "Drip Irrigation & Canal Water Log",
    description:
      "Completed 4th irrigation cycle using canal supply supplemented with tube-well drip irrigation for 5 hours per plot. Soil moisture reading at 65% field capacity.",
    timestamp: "2026-01-28T16:00:00Z",
    location: "Karnal, Haryana",
    cropName: "Wheat",
    metrics: { water_liters: 12000, area_acres: 3 },
    tags: ["Drip Irrigation", "Canal Water", "Field Capacity"],
    isVerified: false,
    isPinned: false,
    isSaved: false,
    importance: "medium",
    source: "manual",
    updatedAt: "2026-01-28T16:00:00Z",
  },
  {
    id: "mem-5",
    category: "fertilizer",
    title: "Basal Fertilizer Application (N P K)",
    description:
      "Applied DAP (50kg/acre) and Urea (45kg/acre) split dose during first irrigation stage. Second dose of Urea planned at 30 days after sowing.",
    timestamp: "2025-11-15T08:30:00Z",
    location: "Karnal, Haryana",
    cropName: "Wheat",
    tags: ["DAP", "Urea", "Nutrient Management", "Split Dose"],
    isVerified: true,
    isPinned: false,
    isSaved: true,
    importance: "medium",
    source: "manual",
    updatedAt: "2025-11-15T08:30:00Z",
  },
  {
    id: "mem-6",
    category: "weather_decisions",
    title: "Early Sowing Decision Based on Weather Forecast",
    description:
      "KisanGPT predicted early monsoon arrival. Decided to advance wheat sowing by 10 days. Resulted in better root establishment before first irrigation.",
    timestamp: "2025-10-25T11:00:00Z",
    location: "Karnal, Haryana",
    cropName: "Wheat",
    tags: ["Early Sowing", "Monsoon", "Weather Forecast"],
    isVerified: true,
    isPinned: false,
    isSaved: true,
    importance: "medium",
    source: "chat",
    relatedConversationId: "conv-weather-003",
    aiExplanation:
      "Early sowing based on weather intelligence allowed the wheat crop to establish stronger root systems before the cold wave in December. This decision contributed to the above-average yield of 24.5 qtl/acre.",
    updatedAt: "2025-10-25T11:00:00Z",
  },
  {
    id: "mem-7",
    category: "market_decisions",
    title: "Wheat Sale at Karnal APMC — Price Timing",
    description:
      "Held wheat stock for 2 weeks after harvest waiting for price improvement. Price rose from ₹2,180 to ₹2,275/qtl. Earned ₹28,500 extra on 32.5 qtl total.",
    timestamp: "2026-04-20T14:30:00Z",
    location: "Karnal APMC, Haryana",
    cropName: "Wheat (PBW 550)",
    tags: ["Price Timing", "APMC", "Revenue"],
    isVerified: true,
    isPinned: true,
    isSaved: true,
    importance: "high",
    source: "chat",
    relatedConversationId: "conv-market-002",
    aiExplanation:
      "Strategic holding of wheat post-harvest yielded ₹95/qtl price improvement. KisanGPT market alerts correctly predicted the upward trend based on government MSP announcements and reduced supply in regional mandis.",
    updatedAt: "2026-04-20T14:30:00Z",
  },
  {
    id: "mem-8",
    category: "govt_schemes",
    title: "PM-KISAN Installment Received",
    description:
      "Received 18th installment of ₹2,000 under PM-KISAN Samman Nidhi. Total received this year: ₹6,000. Aadhaar linked and land records verified.",
    timestamp: "2026-03-10T09:00:00Z",
    location: "Karnal, Haryana",
    tags: ["PM-KISAN", "Installment", "Government Benefit"],
    isVerified: true,
    isPinned: false,
    isSaved: true,
    importance: "medium",
    source: "auto",
    aiExplanation:
      "You have received all 3 installments of PM-KISAN for the current financial year. Ensure your Aadhaar and land records remain updated for uninterrupted benefits in the next cycle.",
    updatedAt: "2026-03-10T09:00:00Z",
  },
  {
    id: "mem-9",
    category: "voice_conversations",
    title: "Voice Query: Best time to irrigate wheat",
    description:
      "Asked KisanGPT in Hindi about optimal irrigation timing. Recommended early morning (6-8 AM) or late evening (4-6 PM) to minimize evaporation losses.",
    timestamp: "2026-01-20T07:30:00Z",
    location: "Karnal, Haryana",
    cropName: "Wheat",
    tags: ["Voice Query", "Irrigation Timing", "Hindi"],
    isVerified: true,
    isPinned: false,
    isSaved: false,
    importance: "low",
    source: "voice",
    relatedConversationId: "conv-voice-005",
    updatedAt: "2026-01-20T07:30:00Z",
  },
  {
    id: "mem-10",
    category: "saved_ai_advice",
    title: "AI Recommendation: Crop Rotation with Mustard",
    description:
      "KisanGPT recommended rotating wheat with Mustard (Sarson) or Moong pulse for the upcoming season. Will restore organic nitrogen and reduce fertilizer costs by 15%.",
    timestamp: "2026-07-15T12:00:00Z",
    tags: ["Crop Rotation", "Mustard", "Cost Saving"],
    isVerified: false,
    isPinned: false,
    isSaved: true,
    importance: "medium",
    source: "chat",
    relatedConversationId: "conv-advice-004",
    aiExplanation:
      "Crop rotation with leguminous crops like Moong fixes atmospheric nitrogen in the soil. Mustard has a shorter duration and can fit between Rabi and Kharif seasons, providing additional income while improving soil health.",
    updatedAt: "2026-07-15T12:00:00Z",
  },
  {
    id: "mem-11",
    category: "custom_note",
    title: "Field 2 Boundary Wall Repair Needed",
    description:
      "Noticed crack in eastern boundary wall near canal head. Need to arrange brick masonry repair before next monsoon season. Estimated cost: ₹8,000-10,000.",
    timestamp: "2026-06-01T08:00:00Z",
    location: "Karnal, Haryana",
    tags: ["Maintenance", "Boundary Wall", "Repair"],
    isVerified: false,
    isPinned: false,
    isSaved: false,
    importance: "low",
    source: "manual",
    updatedAt: "2026-06-01T08:00:00Z",
  },
  {
    id: "mem-12",
    category: "crop_yield",
    title: "Kharif Paddy Harvest (PR 121)",
    description:
      "Harvested PR 121 paddy variety. Yield: 28 quintals per acre across 3 acres. Sold at Minimum Support Price ₹2,320/qtl. Total revenue: ₹1,96,800.",
    timestamp: "2025-11-10T14:00:00Z",
    location: "Karnal, Haryana",
    cropName: "Paddy (PR 121)",
    season: "Kharif 2025",
    metrics: { yield_quintals: 28, area_acres: 3 },
    tags: ["Kharif", "Paddy", "MSP", "PR 121"],
    isVerified: true,
    isPinned: false,
    isSaved: true,
    importance: "high",
    source: "manual",
    aiExplanation:
      "PR 121 paddy yield of 28 qtl/acre is well above the state average of 24 qtl/acre. Your consistent water management and timely fertilizer application contributed to this strong performance.",
    updatedAt: "2025-11-10T14:00:00Z",
  },
];

export const MOCK_RECOMMENDATIONS: PersonalizedRecommendation[] = [
  {
    id: "rec-1",
    title: "Potassium Top-Dressing Recommended for Field 2",
    description:
      "Based on your June 2026 soil test showing 110 kg/ha Potassium, apply MOP (Muriate of Potash) @ 20kg/acre during next crop cycle to prevent leaf tip burning.",
    impact: "high",
    category: "Soil & Nutrient Management",
    actionLabel: "View Nutrient Advice",
    targetRoute: "/chat",
    dateGenerated: "2026-07-20T08:00:00Z",
    basedOnMemories: ["mem-1", "mem-5"],
  },
  {
    id: "rec-2",
    title: "Pre-Emptive Rust Monitoring for Next Rabi Season",
    description:
      "Since Yellow Rust was recorded in your farm history in Feb 2026, select resistant wheat varieties like DBW 187 or HD 3226 for the upcoming sowing season.",
    impact: "high",
    category: "Crop Protection",
    actionLabel: "Ask KisanGPT Doctor",
    targetRoute: "/disease",
    dateGenerated: "2026-07-18T10:00:00Z",
    basedOnMemories: ["mem-3"],
  },
  {
    id: "rec-3",
    title: "Optimal Paddy-to-Mustard Crop Rotation Advice",
    description:
      "Your historical yield logs show 24.5 qtl/acre wheat yield. Rotating with Mustard (Sarson) or Moong pulse will restore organic nitrogen and cut fertilizer expense by 15%.",
    impact: "medium",
    category: "Crop Planning",
    actionLabel: "Explore Crop Trends",
    targetRoute: "/market",
    dateGenerated: "2026-07-15T12:00:00Z",
    basedOnMemories: ["mem-1", "mem-2"],
  },
];

export const MOCK_AI_INSIGHTS: AIMemoryInsight[] = [
  {
    id: "insight-1",
    type: "recurring_issue",
    title: "Rust Risk Pattern Detected",
    description:
      "Yellow rust has appeared in your wheat crop during the last 2 consecutive Rabi seasons. Consider preventive fungicide spraying in December.",
    confidence: 0.92,
    relatedMemories: ["mem-3"],
    actionable: true,
    actionLabel: "View Disease Prevention",
    targetRoute: "/disease",
    icon: "🔄",
  },
  {
    id: "insight-2",
    type: "frequent_question",
    title: "Irrigation Timing Queries",
    description:
      "You have asked about irrigation timing 5 times in the past 3 months. We recommend setting a fixed schedule: 6 AM on Mondays and Thursdays.",
    confidence: 0.88,
    relatedMemories: ["mem-4", "mem-9"],
    actionable: true,
    actionLabel: "Set Irrigation Schedule",
    targetRoute: "/weather",
    icon: "❓",
  },
  {
    id: "insight-3",
    type: "decision_pattern",
    title: "Smart Price Holding Strategy",
    description:
      "You successfully timed 2 wheat sales in the past year, earning ₹28,500 extra by holding stock. This pattern shows strong market awareness.",
    confidence: 0.95,
    relatedMemories: ["mem-7", "mem-2"],
    actionable: false,
    icon: "📈",
  },
  {
    id: "insight-4",
    type: "crop_performance",
    title: "Above-Average Yields Across Crops",
    description:
      "Your wheat (24.5 qtl/acre) and paddy (28 qtl/acre) yields consistently exceed Haryana state averages. Your fertilizer and irrigation practices are well-optimized.",
    confidence: 0.97,
    relatedMemories: ["mem-2", "mem-12", "mem-5", "mem-4"],
    actionable: false,
    icon: "🌾",
  },
  {
    id: "insight-5",
    type: "seasonal_trend",
    title: "Optimal Sowing Window Approaching",
    description:
      "Based on your past 2 seasons, your ideal wheat sowing window is October 20-November 5. Weather forecasts suggest planning for early November this year.",
    confidence: 0.85,
    relatedMemories: ["mem-6", "mem-2"],
    actionable: true,
    actionLabel: "Check Weather Forecast",
    targetRoute: "/weather",
    icon: "📅",
  },
  {
    id: "insight-6",
    type: "suggested_improvement",
    title: "Organic Carbon Needs Attention",
    description:
      "Your soil OC at 0.42% is below the recommended 0.75%. Adding 5-7 tonnes/acre of farmyard manure before sowing will improve soil health within 2 seasons.",
    confidence: 0.91,
    relatedMemories: ["mem-1"],
    actionable: true,
    actionLabel: "View Soil Advice",
    targetRoute: "/chat",
    icon: "💡",
  },
];

export const MOCK_HERO_STATS: MemoryHeroStats = {
  totalMemories: 12,
  recentUpdates: 4,
  pinnedCount: 3,
  savedCount: 7,
  verifiedCount: 9,
  categoryBreakdown: [
    { category: "soil", count: 1, label: "Soil" },
    { category: "crop_yield", count: 2, label: "Crops" },
    { category: "disease_history", count: 1, label: "Diseases" },
    { category: "irrigation", count: 1, label: "Irrigation" },
    { category: "fertilizer", count: 1, label: "Fertilizer" },
    { category: "weather_decisions", count: 1, label: "Weather" },
    { category: "market_decisions", count: 1, label: "Market" },
    { category: "govt_schemes", count: 1, label: "Schemes" },
    { category: "voice_conversations", count: 1, label: "Voice" },
    { category: "saved_ai_advice", count: 1, label: "AI Advice" },
    { category: "custom_note", count: 1, label: "Notes" },
  ],
};

export const SOURCE_CONFIG: Record<
  string,
  { label: string; color: string; bg: string }
> = {
  chat: { label: "Chat", color: "text-emerald-600", bg: "bg-emerald-500/10" },
  voice: { label: "Voice", color: "text-pink-600", bg: "bg-pink-500/10" },
  manual: {
    label: "Manual",
    color: "text-blue-600",
    bg: "bg-blue-500/10",
  },
  auto: { label: "Auto", color: "text-violet-600", bg: "bg-violet-500/10" },
  scan: { label: "Scan", color: "text-amber-600", bg: "bg-amber-500/10" },
};

export const IMPORTANCE_CONFIG: Record<
  string,
  { label: string; color: string; bg: string }
> = {
  high: {
    label: "High",
    color: "text-red-600",
    bg: "bg-red-500/10",
  },
  medium: {
    label: "Medium",
    color: "text-amber-600",
    bg: "bg-amber-500/10",
  },
  low: {
    label: "Low",
    color: "text-slate-500",
    bg: "bg-slate-500/10",
  },
};
